#!/bin/bash
echo "getting librAIry dependencies .."
docker stop test || true && docker rm test || true
docker run -it --name test -v "$PWD":/usr/src/mymaven -w /usr/src/mymaven maven:3.5.2-jdk-8-alpine mvn -Dmaven.repo.local=/usr/src/mymaven/.m2/repository clean test
export PATH=".:$PATH"
echo "librAIry is ready for use"
